# Default values for navigator

replicaCount: 1

image:
  repository: navigator-registry:5000/navigator-server
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 50051

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# Server configuration
server:
  logLevel: info
